document.addEventListener("DOMContentLoaded", () => {
  ThemeManager.init();
  document.getElementById("theme-toggle")
    .addEventListener("click", () => ThemeManager.toggle());
});

let currentTabId = null;
let currentDomain = "";
let detectedFields = [];
let savedPersona = null;
let activePersona = null;
let currentPlan = "free";
let currentUsage = { count: 0, date: "" };
let currentFillMode = "ai";
let currentProvider = "gemini";
let activeSourceLabel = "";

const statusEl = document.getElementById("status");
const errorEl = document.getElementById("error");
const planBadgeEl = document.getElementById("planBadge");
const personaCardEl = document.getElementById("personaCard");
const savedNoteEl = document.getElementById("savedNote");
const sourceTagEl = document.getElementById("sourceTag");
const customFieldsCardEl = document.getElementById("customFieldsCard");
const personaNameEl = document.getElementById("personaName");
const personaEmailEl = document.getElementById("personaEmail");
const personaPhoneEl = document.getElementById("personaPhone");
const generateBtn = document.getElementById("generateBtn");
const savedBtn = document.getElementById("savedBtn");
const usageEl = document.getElementById("usage");
const settingsLink = document.getElementById("settingsLink");
const fillModePill = document.getElementById("fillModePill");
const modeSwitchButtons = Array.from(document.querySelectorAll(".switch-pill"));

function getToday() {
  return new Date().toISOString().slice(0, 10);
}

function openSettings(tabName) {
  if (tabName) {
    chrome.tabs.create({ url: chrome.runtime.getURL(`options/options.html#${tabName}`) });
    return;
  }

  chrome.runtime.openOptionsPage();
}

function setError(html) {
  errorEl.innerHTML = html;
  errorEl.style.display = html ? "block" : "none";

  const link = errorEl.querySelector("[data-open-settings]");

  if (link) {
    link.addEventListener("click", () => openSettings("ai"));
  }
}

function updateGenerateButton(isLoading) {
  generateBtn.disabled = isLoading;
  savedBtn.disabled = isLoading || !savedPersona;

  if (currentFillMode === "profile") {
    generateBtn.textContent = "Fill with my profile";
    return;
  }

  generateBtn.innerHTML = isLoading
    ? '<span class="spinner"></span>Generating...'
    : "✨ Generate ghost persona";
}

function setLoading(isLoading) {
  updateGenerateButton(isLoading);
}

function updateFillModeUi() {
  const isProfileMode = currentFillMode === "profile";
  fillModePill.textContent = isProfileMode ? "👤 Profile mode" : "🤖 AI mode";
  fillModePill.classList.toggle("profile", isProfileMode);
  updateGenerateButton(false);

  modeSwitchButtons.forEach((button) => {
    button.classList.toggle("active", button.dataset.mode === currentFillMode);
  });
}

function updatePlanBadge() {
  const isPro = currentPlan === "pro";
  planBadgeEl.textContent = isPro ? "Pro" : "Free";
  planBadgeEl.classList.toggle("pro", isPro);
}

function updateUsageIndicator() {
  usageEl.classList.remove("limit");

  if (currentPlan !== "free") {
    usageEl.textContent = "";
    return;
  }

  const count = currentUsage.date === getToday() ? currentUsage.count : 0;

  if (count >= 3) {
    usageEl.classList.add("limit");
    usageEl.innerHTML = 'Limit reached - Upgrade to Pro <a id="upgradeLink">Upgrade →</a>';
    document.getElementById("upgradeLink").addEventListener("click", () => openSettings("plan"));
    return;
  }

  usageEl.textContent = `${count} / 3 free fills used today`;
}

function updateFieldStatus() {
  const count = detectedFields.length;
  statusEl.textContent = count === 0
    ? "No form fields detected on this page"
    : `Found ${count} fields`;
}

function getSourceLabel(response, isFromVault) {
  if (response && response.source === "profile") {
    return "From your profile";
  }

  if (response && response.provider === "claude") {
    return "Generated by Claude";
  }

  if (response && response.provider === "gemini") {
    return "Generated by Gemini";
  }

  if (isFromVault) {
    return activeSourceLabel || "Saved persona";
  }

  return currentFillMode === "profile"
    ? "From your profile"
    : `Generated by ${currentProvider === "claude" ? "Claude" : "Gemini"}`;
}

function createCustomFieldRow(customField, index) {
  const row = document.createElement("div");
  row.className = "persona-row";

  const label = document.createElement("div");
  label.className = "persona-label";
  label.textContent = customField.label || customField.key || `Field ${index + 1}`;
  label.title = label.textContent;

  const value = document.createElement("div");
  value.className = "persona-value";
  value.textContent = customField.value || "";
  value.title = value.textContent;

  const copyButton = document.createElement("button");
  copyButton.className = "copy-btn";
  copyButton.dataset.customIndex = String(index);
  copyButton.title = `Copy ${label.textContent}`;
  copyButton.textContent = "📋";

  row.append(label, value, copyButton);
  return row;
}

function renderCustomFields(persona) {
  customFieldsCardEl.textContent = "";

  const customFields = Array.isArray(persona.customFields) ? persona.customFields : [];
  customFields
    .filter((field) => field && field.value !== undefined && field.value !== null && field.value !== "")
    .forEach((field, index) => {
      customFieldsCardEl.appendChild(createCustomFieldRow(field, index));
    });
}

function displayPersona(persona, isFromVault, response) {
  activePersona = persona;
  activeSourceLabel = getSourceLabel(response, isFromVault);

  const fullName = [persona.firstName, persona.lastName].filter(Boolean).join(" ");
  personaNameEl.textContent = fullName || "";
  personaEmailEl.textContent = persona.email || "";
  personaPhoneEl.textContent = persona.phone || "";
  sourceTagEl.textContent = activeSourceLabel;
  renderCustomFields(persona);
  personaCardEl.classList.add("visible");
  savedNoteEl.classList.toggle("visible", Boolean(isFromVault));
}

function sendTabMessage(message) {
  return new Promise((resolve, reject) => {
    chrome.tabs.sendMessage(currentTabId, message, (response) => {
      const error = chrome.runtime.lastError;

      if (error) {
        reject(error);
        return;
      }

      resolve(response);
    });
  });
}

function sendRuntimeMessage(message) {
  return new Promise((resolve, reject) => {
    chrome.runtime.sendMessage(message, (response) => {
      const error = chrome.runtime.lastError;

      if (error) {
        reject(error);
        return;
      }

      resolve(response);
    });
  });
}

async function getCurrentTab() {
  const tabs = await chrome.tabs.query({ active: true, currentWindow: true });
  return tabs[0];
}

async function loadTabContext() {
  const tab = await getCurrentTab();
  currentTabId = tab.id;
  currentDomain = new URL(tab.url).hostname;
}

async function loadFields() {
  try {
    const response = await sendTabMessage("GET_FIELDS");
    detectedFields = response && Array.isArray(response.fields) ? response.fields : [];
  } catch (err) {
    detectedFields = [];
  }

  updateFieldStatus();
}

async function loadProviderState() {
  const result = await chrome.storage.local.get("gf_provider");
  currentProvider = result.gf_provider === "claude" ? "claude" : "gemini";
}

async function loadVaultState() {
  currentPlan = await Vault.getPlan();
  currentUsage = await Vault.getUsage();
  currentFillMode = await Vault.getFillMode();
  savedPersona = await Vault.getPersona(currentDomain);

  savedBtn.disabled = !savedPersona;
  updatePlanBadge();
  updateUsageIndicator();
  updateFillModeUi();
}

async function refreshUsageState() {
  currentUsage = await Vault.getUsage();
  updateUsageIndicator();
}

function showApiKeyPrompt(provider) {
  const providerName = provider === "claude" ? "Claude" : "Gemini";
  setError(`${providerName} API key not set. Go to <a data-open-settings>Settings →</a>`);
}

function showUpgradeMessage() {
  usageEl.classList.add("limit");
  usageEl.innerHTML = 'Limit reached - Upgrade to Pro <a id="upgradeLink">Upgrade →</a>';
  document.getElementById("upgradeLink").addEventListener("click", () => openSettings("plan"));
}

async function handleGenerateClick() {
  setError("");
  setLoading(currentFillMode === "ai");

  try {
    const response = await sendRuntimeMessage({
      type: "GENERATE_PERSONA",
      fields: detectedFields,
      domain: currentDomain
    });

    if (response && response.success) {
      savedPersona = response.persona;
      savedBtn.disabled = false;
      displayPersona(response.persona, false, response);
      await sendTabMessage({ type: "FILL_FIELDS", persona: response.persona });
      await refreshUsageState();
      return;
    }

    if (response && response.error === "LIMIT_REACHED") {
      showUpgradeMessage();
      return;
    }

    if (response && response.error === "NO_API_KEY") {
      showApiKeyPrompt(response.provider);
      return;
    }

    setError("Something went wrong. Check your API key in Settings.");
  } catch (err) {
    setError("Something went wrong. Check your API key in Settings.");
  } finally {
    setLoading(false);
  }
}

async function handleSavedClick() {
  setError("");
  const persona = await Vault.getPersona(currentDomain);

  if (!persona) {
    savedPersona = null;
    savedBtn.disabled = true;
    return;
  }

  savedPersona = persona;
  displayPersona(persona, true);
  await sendTabMessage({ type: "FILL_FIELDS", persona });
}

async function handleCopyClick(event) {
  const button = event.target.closest(".copy-btn");

  if (!button || !activePersona) {
    return;
  }

  const customIndex = button.dataset.customIndex;
  const customFields = Array.isArray(activePersona.customFields) ? activePersona.customFields : [];
  const copyType = button.dataset.copy;
  const value = customIndex !== undefined
    ? customFields[Number(customIndex)] && customFields[Number(customIndex)].value
    : copyType === "name"
      ? [activePersona.firstName, activePersona.lastName].filter(Boolean).join(" ")
      : activePersona[copyType];

  if (!value) {
    return;
  }

  await navigator.clipboard.writeText(value);
  button.textContent = "✓";

  setTimeout(() => {
    button.textContent = "📋";
  }, 1500);
}

async function switchFillMode(mode) {
  currentFillMode = mode === "profile" ? "profile" : "ai";
  await Vault.setFillMode(currentFillMode);
  updateFillModeUi();
}

async function init() {
  settingsLink.addEventListener("click", () => openSettings());
  fillModePill.addEventListener("click", () => {
    openSettings(currentFillMode === "profile" ? "profile" : "ai");
  });
  generateBtn.addEventListener("click", handleGenerateClick);
  savedBtn.addEventListener("click", handleSavedClick);
  personaCardEl.addEventListener("click", handleCopyClick);
  modeSwitchButtons.forEach((button) => {
    button.addEventListener("click", () => switchFillMode(button.dataset.mode));
  });

  try {
    await loadTabContext();
    await Promise.all([loadFields(), loadProviderState(), loadVaultState()]);
  } catch (err) {
    statusEl.textContent = "Unable to scan this page";
  }
}

document.addEventListener("DOMContentLoaded", init);
